# -*- coding: utf-8 -*-
"""env.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhiewcUk2JyG-ERAReF78N-eY-rGdpcy
"""

import numpy as np
import pandas as pd
import gymnasium as gym #permet de creer des env d'apprentissage pour agents
from gymnasium import spaces #permet de définir les régles de l'env

class TradingEnv(gym.Env):
  metadata = {"render_modes": ["human"]}
  def __init__(self,data:pd.DataFrame,window_size:int=20,initial_balance:float=10_000.0,transaction_cost:float=0.001,render_modes=None):
    super().__init__()
    self.data = data
    self.window_size = window_size
    self.initial_balance = initial_balance
    self.transaction_cost = transaction_cost
    self.render_modes = render_modes
    self.n_features=self.data.shape[1]

    obs_size=self.window_size*self.n_features+2 #2 pour les info de portfeuille (position et le cash_ratio)
    self.observation_space=spaces.Box(
        low=-np.inf,
        high=np.inf,
        shape=(obs_size,),
        dtype=np.float32,
    )
    self.action_space = spaces.Discrete(3)

    self.current_step  = 0
    self.balance       = initial_balance
    self.shares_held   = 0  #nbre d'action
    self.net_worth     = initial_balance #cash + valeur des actions
    self.prev_worth    = initial_balance
    self.position      = 0

  def _current_price(self):
    returns=self.data[:self.current_step + self.window_size, 6]
    price = 100.0 * np.prod(1 + np.clip(returns, -0.5, 0.5))
    return max(price, 1.0)

  def _get_obs(self) -> np.ndarray:
    start = self.current_step
    end   = start + self.window_size
    window = self.data[start:end].flatten()

    cash_ratio  = np.float32(self.balance / (self.net_worth + 1e-9))
    position    = np.float32(self.position)

    return np.concatenate([window, [position, cash_ratio]])

  def reset(self, seed=None, options=None):
    super().reset(seed=seed)

    self.current_step = 0
    self.balance      = self.initial_balance
    self.shares_held  = 0
    self.net_worth    = self.initial_balance
    self.prev_worth   = self.initial_balance
    self.position     = 0

    return self._get_obs(), {}

  def step(self, action: int):
    price = self._current_price()
    if action == 1:
        if self.position == 0 and self.balance > price:
            shares_to_buy     = self.balance / (price * (1 + self.transaction_cost))
            cost              = shares_to_buy * price * (1 + self.transaction_cost)
            self.balance     -= cost
            self.shares_held += shares_to_buy
            self.position     = 1

    elif action == 2:
        if self.position == 1 and self.shares_held > 0:
            revenue           = self.shares_held * price * (1 - self.transaction_cost)
            self.balance     += revenue
            self.shares_held  = 0
            self.position     = 0

    self.net_worth = self.balance + self.shares_held * price

    reward = np.log(self.net_worth / (self.prev_worth + 1e-9))
    self.prev_worth = self.net_worth

    self.current_step += 1
    max_steps    = len(self.data) - self.window_size - 1
    terminated   = self.current_step >= max_steps
    truncated    = False

    return self._get_obs(), float(reward), terminated, truncated, {
        "net_worth":   self.net_worth,
        "balance":     self.balance,
        "shares_held": self.shares_held,
    }

  def render(self):
    price = self._current_price()
    pos   = "LONG" if self.position == 1 else "NEUTRE"
    print(f"  Étape {self.current_step:4d} | "
          f"Prix ~{price:8.2f} | "
          f"Valeur {self.net_worth:10.2f} $ | "
          f"Position: {pos}")

class MultiStockEnv(gym.Env):

  def __init__(self,
                stock_data: dict[str, pd.DataFrame],
                window_size: int = 20,
                initial_balance: float = 10_000.0,
                transaction_cost: float = 0.001):

      super().__init__()

      self.stock_data       = stock_data
      self.tickers          = list(stock_data.keys())
      self.window_size      = window_size
      self.initial_balance  = initial_balance
      self.transaction_cost = transaction_cost
      self.current_ticker   = self.tickers[0]

      tmp_env = TradingEnv(
          list(stock_data.values())[0],
          window_size=window_size
      )
      self.observation_space = tmp_env.observation_space
      self.action_space      = tmp_env.action_space
      self._env              = tmp_env

  def _make_env(self, ticker: str) -> TradingEnv:
      return TradingEnv(
          self.stock_data[ticker],
          window_size=self.window_size,
          initial_balance=self.initial_balance,
          transaction_cost=self.transaction_cost,
      )

  def reset(self, seed=None, options=None):
      self.current_ticker = np.random.choice(self.tickers)
      self._env = self._make_env(self.current_ticker)
      obs, info = self._env.reset(seed=seed)
      info["ticker"] = self.current_ticker
      return obs, info

  def step(self, action):
      obs, reward, terminated, truncated, info = self._env.step(action)
      info["ticker"] = self.current_ticker
      return obs, reward, terminated, truncated, info

  def render(self):
      print(f"  [Action: {self.current_ticker}] ", end="")
      self._env.render()